language: perl

perl:
    - "5.16"
    - "5.14"
    - "5.12"

install:
    - cpanm Dist::Zilla --quiet --notest
    - dzil authordeps | xargs cpanm --quiet --notest
    - dzil listdeps | xargs cpanm --quiet --notest
